import {
  addComponent,
  addImports,
  addTemplate,
  createResolver,
  defineNuxtModule,
  useLogger,
} from '@nuxt/kit';
import type { Component } from '@nuxt/schema';
import * as fs from 'node:fs';
import { promises as fsp } from 'node:fs';
import * as path from 'node:path';
import { generateIconsIndex, generateIconsRegistry } from './files-generation/generate-icon-index';
import { createSvgComponentCode } from './render/svg-codegen';
import { vueSFCWrapper } from './render/vue-sfc-wrapper';
import type { ComposeIconSize } from './runtime/types/icon-sizes';
import { assertAbsolute } from './runtime/types/path';
import {
  createComponentFromName,
  generateComponentName,
  generateCssFile,
  optimizeSvg,
  readDirectoryRecursively,
  writeComponentFile,
} from './utils';
import { createDir, writeFile } from './utils/filesystem/helpers';
import { optimizeCss } from './utils/styles/optimize-css';

/**
 * Rollup plugin for Nitro that handles script-only .vue SFCs generated by this module.
 * Nitro's Rollup has no Vue plugin, so this extracts the <script> block content
 * so Nitro's TypeScript transformer can process icon components.
 */
function createVueScriptPlugin(componentsDir: string) {
  return {
    name: 'compose-icons-vue-script',
    resolveId(id: string, importer: string | undefined) {
      if (!id.endsWith('.vue') || !importer) return null;
      const resolved = path.resolve(path.dirname(importer), id);
      return resolved.startsWith(componentsDir) ? resolved : null;
    },
    transform(code: string, id: string) {
      if (!id.endsWith('.vue') || !id.startsWith(componentsDir)) return null;
      const match = code.match(/<script(?:\s[^>]*)?>([^]*?)<\/script>/);
      return match?.[1] ? { code: match[1].trim(), map: null } : null;
    },
  };
}
export interface GeneratedComponentOptions {
  /**
   * The prefix to use for the component
   *
   * @type {?string}
   * @default undefined
   */
  prefix?: string;

  /**
   * The suffix to use for the component
   *
   * @type {?string}
   * @default "Icon" ( PascalCase ) and "-icon" ( kebab-case )
   */
  suffix?: string;

  /**
   * Case to use for the component name
   *
   * @type {'pascal' | 'kebab'}
   * @default "pascal" ( PascalCase ) and "kebab" ( kebab-case )
   */
  case: 'pascal' | 'kebab';

  /**
   * Wether to create an index file or not in the components directory
   *
   * @type {boolean}
   * @default false
   */
  hasIndexFile?: boolean;

  /**
   * TODO: The directory to save the generated components
   *
   * @type {?string}
   * @default "runtime/components/icons-generated"
   */
  componentsDestDir?: string;

  /**
   * CSS Classes to apply to the generated components
   *
   * @type {?string[]}
   * @default []
   */
  iconClasses?: string | string[];

  /**
   * Format of the generated component file, either as a Vue SFC (.vue) or as a TypeScript file (.ts)
   *
   * @type {?('vue' | 'ts')}
   * @default 'vue'
   */
  fileFormat?: 'vue' | 'ts';
}

export interface NuxtComposeIconsOptions {
  /**
   * Wether or not to run the module at every appplication build
   * default: true
   *
   * @type {?boolean}
   */
  reRunOnBuild?: boolean;

  /*
   * The path to the icons directory
   */
  pathToIcons?: string;

  /**
   * TODO: An object containing icon components to register
   * e.g. { 'custom-icon': CustomIconComponent }
   * This allows to register custom icon components directly without generating them from SVG files
   * Useful for registering third-party icon libraries or custom components
   * Note: The keys will be used as the component names (with prefix/suffix and case applied)
   * e.g. { 'custom-icon': CustomIconComponent } will be registered as "CustomIcon" or "custom-icon-icon" depending on the case option
   * default: {}
   *
   * @type {?{ [key: string]: Component }}
   */
  iconComponentList?: { [key: string]: Component };

  /**
   * The icon sizes to generate CSS classes for
   * default:
   * {
   *   xs: '0.5rem',
   *   sm: '0.875rem',
   *   md: '1rem',
   *   lg: '1.5rem',
   *   xl: '2.5rem',
   * }
   *
   * @type {?IconSizes}
   */
  iconSizes?: ComposeIconSize;

  /**
   * @type {GeneratedComponentOptions}
   */
  generatedComponentOptions: GeneratedComponentOptions;

  /**
   * Dry run mode: log the component names and paths without writing files
   *
   * @type {?boolean}
   * @default false
   */
  dryRun?: boolean;

  /**
   * Show additional logs than warnings and errors
   *
   * @type {?boolean}
   */
  debug?: boolean;
}

export default defineNuxtModule<NuxtComposeIconsOptions>({
  meta: {
    name: 'nuxt-compose-icons',
    configKey: 'composeIcons',
    compatibility: {
      // Required nuxt version in semver format.
      nuxt: '>=3.0.0', // or use '^3.0.0'
    },
  },
  // Default configuration options of the Nuxt module
  defaults: {
    reRunOnBuild: true,
    // iconSizes: {
    //   [IconSize.XS]: '0.5rem',
    //   [IconSize.SM]: '0.875rem',
    //   [IconSize.MD]: '1rem',
    //   [IconSize.LG]: '1.5rem',
    //   [IconSize.XL]: '2.5rem',
    // },
    // If not provided, the default will be to use the "Icon" suffix for the component without a prefix
    // e.g. "arrow-up.svg" will be "ArrowUpIcon"

    generatedComponentOptions: {
      prefix: undefined,
      suffix: 'Icon',
      case: 'pascal',
      componentsDestDir: undefined,
      iconClasses: 'compose-icon',
      fileFormat: 'vue',
    },
    iconComponentList: {},
  },

  hooks: {
    'build:before'() {},
  },
  async setup(options, nuxt) {
    // const logger = useLogger('nuxt-compose-icons', {
    //   reporters: [
    //     {
    //       log(log) {
    //         if (log.type === 'error' || log.type === 'warn') {
    //           console[log.type](`[${log.type.toUpperCase()}]`, ...log.args);
    //         } else if (log.type === 'info' && options.debug) {
    //           console.log(`[DEBUG]`, ...log.args);
    //         }
    //       },
    //     },
    //   ],
    // });
    const logger = useLogger('nuxt-compose-icons');
    const { resolve } = createResolver(import.meta.url);

    /**
     * Resolver for everything related to the user's app directory
     *
     * @param {...string[]} p
     * @returns {*}
     */
    function resolveApp(...p: string[]) {
      return path.resolve(nuxt.options.rootDir, ...p);
    } // app base

    /**
     * Resolver for everything related to the Nuxt build directory
     *
     * @param {...string[]} p
     * @returns {*}
     */
    function resolveBuild(...p: string[]) {
      return path.resolve(nuxt.options.buildDir, ...p);
    }

    /**
     * Nuxt version detection and compatibility handling
     * TODO: isNuxtMajorVersion and assertNuxtCompatibility were producing errors if used on certain Nuxt 3 versions
     */
    const nuxtMajor = Number.parseInt(nuxt._version.split('.')[0]);
    // Nuxt 3 can opt into Nuxt 4 behaviour via future.compatibilityVersion
    const compatVersion = (
      nuxt.options as unknown as Record<string, unknown> & {
        future?: { compatibilityVersion?: number };
      }
    ).future?.compatibilityVersion;
    const effectiveMajor = compatVersion ?? nuxtMajor;

    if (effectiveMajor >= 4) {
      logger.info('✅ - Nuxt 4 detected');
    } else if (nuxtMajor === 3) {
      logger.info('✅ - Nuxt 3 detected');
    } else {
      logger.warn(`⚠️ - Nuxt ${nuxtMajor} detected, compatibility not guaranteed`);
    }

    // Prevent Vite's dep pre-bundling from running esbuild on the composables
    // before this module has a chance to register the #compose-icons/registry alias.
    nuxt.options.vite.optimizeDeps ??= {};
    nuxt.options.vite.optimizeDeps.exclude = [
      ...(nuxt.options.vite.optimizeDeps.exclude ?? []),
      'nuxt-compose-icons',
    ];

    const { reRunOnBuild, pathToIcons, iconComponentList, iconSizes } = options;

    if (!reRunOnBuild) {
      logger.info('⚠️ - reRunOnBuild is disabled, the module will run only once at setup');
      return;
    }

    if (!pathToIcons && !iconComponentList) {
      logger.error(
        'You must provide either pathToIcons or iconComponentList in the module options.',
      );
      throw new Error('pathToIcons or iconComponentList is required');
    }

    // Set a directory where the icons will be generated if no componentsDestDir is provided
    // .nuxt/compose-icons
    const defaultDir = resolveBuild('compose-icons');

    if (!options.generatedComponentOptions.componentsDestDir) {
      logger.info(
        '⚠️ - No directory is set, using default directory → ',
        defaultDir,
        '\n To set a custom directory, use the generatedComponentOptions.componentsDestDir option.',
      );
    }

    const userDir = options.generatedComponentOptions.componentsDestDir;

    const componentsDir = assertAbsolute(
      userDir ? (path.isAbsolute(userDir) ? userDir : resolveApp(userDir)) : defaultDir,
    );

    await createDir(componentsDir);

    if (pathToIcons) {
      // Resolve the path to the icons directory provided
      const absolutePathToIcons = assertAbsolute(
        path.isAbsolute(pathToIcons) ? pathToIcons : resolveApp(pathToIcons),
      );

      if (fs.existsSync(absolutePathToIcons) && fs.statSync(absolutePathToIcons).isDirectory()) {
        // We first read all the files recursively to flatten the structure
        const files = await readDirectoryRecursively(absolutePathToIcons);

        // List of generated Icon components
        const generatedComponents: Component[] = [];

        /*
         * Dry run mode: log the component names and paths without writing files
         */
        if (options.dryRun) {
          nuxt.hook('build:before', () => {
            logger.info(`🔍 Dry-run mode: No files will be written.`);
            files.forEach((file) => {
              const fileInfo = path.parse(file);
              const name = generateComponentName(fileInfo.name, options);
              logger.info(`${fileInfo.base} Would generate: ${name}`);
            });
            process.exit();
          });
        }

        // Set Icon classes (can be set to ensure consistency in a Design System for example)
        const iconClasses = Array.isArray(options.generatedComponentOptions.iconClasses)
          ? options.generatedComponentOptions.iconClasses
          : [options.generatedComponentOptions.iconClasses];

        // We ensure the base class is always included to allow styling the icons with a common class, used by default CSS
        // TODO: Let the user fully set the base class https://github.com/arthur-plazanet/nuxt-compose-icons/issues/312
        iconClasses.push('compose-icon'); // Ensure the base class is always included

        /*
         * For each file we:
         * 1. Parse the content (as HTML/XML string)
         * 2. Optimize with SVGO
         * 3. Generate the component name based on the initial svg file name and the options provided (prefix, suffix, case)
         * 4. Create the component code as literal string template by:
         *   . Recreating the Vue VNode structure dynamically based on the SVG content
         *   . Set the props and attributes based on the SVG content and the options passed
         * 5. Write the component to the file system
         * 6. Create the "official" component object with the name and path
         * 7. Add the component to the Nuxt app's components array at build time
         * 8. Generate a CSS file with the icon sizes and add it to the Nuxt app's CSS array at build time
         * 9. Add composables
         * 10. Generate the icons index file
         * 11. Generate the icon registry file
         *
         * We use a literal string template to create the Vue component
         * see https://nuxt-compose-icons.arthurplazanet.com/why-literal-strings-to-create-vue-components
         */
        // nuxt.hook('build:before', async () => {
        for (const filePath of files) {
          const fileInfo = path.parse(filePath);

          if (fileInfo.ext !== '.svg') {
            continue;
          }

          // 1. Parse the content (as HTML string)
          let svgContent = await fsp.readFile(filePath, 'utf-8');

          // 2. Optimize with SVGO
          svgContent = optimizeSvg(svgContent, {
            iconClasses: options.generatedComponentOptions.iconClasses,
          });

          // TODO: Check if necessary to handle snake case as well

          // TODO: handle double dashes "--", and if ".svg" already present
          const componentName = generateComponentName(fileInfo.name, options);

          // 3. Create the component code as literal string template (.ts fine)
          let componentCode = createSvgComponentCode(componentName, svgContent);

          //4 - if fileFormat is set to "vue", wrap the component code in a Vue SFC <script lang="ts"> block
          //  TODO: See pros and cons https://github.com/arthur-plazanet/nuxt-compose-icons/issues/325
          if (options.generatedComponentOptions.fileFormat === 'vue') {
            componentCode = vueSFCWrapper(componentCode);
          }

          // 4. Write the component to the file system
          const generatedFilePath = await writeComponentFile({
            componentName,
            componentsDir,
            componentCode,
            format: options.generatedComponentOptions.fileFormat,
          });

          // 5. Create the "official" component object with the name and path
          const component = createComponentFromName({
            name: componentName,
            shortPath: generatedFilePath,
            filePath: generatedFilePath,
          });

          // 5.5 Store the component in array for later use
          generatedComponents.push(component);

          // 6. Add the component to the Nuxt app's components array at build time
          // nuxt.hook('components:extend', (components) => {
          // components.push(component);
          // });
          // addComponent({
          //   name: component.pascalName,
          //   filePath: component.filePath,
          // });

          // addImportsSources({
          //   from: resolver.resolve('runtime/types'),
          //   imports: [
          //     {
          //       name: 'types',
          //       as: 'types',
          //     },
          //   ],
          // });
          if (options.debug) {
            logger.info('📟 - defaultDir → ', defaultDir);
            logger.success(`✅ Generated component: ${componentName} from ${fileInfo.base}`);
          }
        }

        // });

        // addComponentsDir({
        //   path: componentsDir,
        //   extensions: ['vue'], // 👈 critical
        //   ignore: ['index.ts', 'icon-registry.ts'],
        //   // prefix: options.generatedComponentOptions.prefix,
        // });

        // 7. Generate a CSS file with the icon sizes and add it to the Nuxt app's CSS array at build time
        const { cssFileContent } = generateCssFile({
          iconSizes,
          iconClasses: options.generatedComponentOptions.iconClasses,
        });

        if (options.debug) {
          logger.info(`📦 - Registering components from ${componentsDir}`);
          logger.info(`📟 - Generated CSS content for icon sizes: ${cssFileContent}`);
        }
        // Define the path to save the CSS file within the module
        // const iconRootVars = resolve('./runtime/assets/compose-sizes.css');
        // await writeFile(iconRootVars, cssContent);
        // nuxt.options.css.push(iconRootVars);

        const baseIconStyles = resolve('runtime/assets/compose-icon.css');

        // await writeFile(baseIconStyles, optimizeCss(cssFileContent));
        // nuxt.options.alias = {
        //   '@': './runtime',
        // };
        // 2. Register a single template that merges them
        nuxt.options.css.push(baseIconStyles);

        // nuxt.options.css.push(tpls.dst); // ✅ this is in buildDir
        // logger.log('📟 - tpl → ', tpl);

        const completeIconStyles = optimizeCss(`${cssFileContent}`);

        const tpl = addTemplate({
          filename: 'compose-icon-sizes.css',
          getContents: () => `${completeIconStyles}`,
        });
        nuxt.options.css.push(tpl.dst);

        //  write file locally
        await writeFile(
          assertAbsolute(resolve('./runtime/assets/compose-icon-sizes.css')),
          `${completeIconStyles}`,
        );

        // addImportsDir(resolve('runtime/types'));
        // addImportsDir(resolve('runtime/utils'));

        // Add built-in components
        // TODO: Make optional?
        addComponent({
          name: 'ComposeIconOverview',
          filePath: resolve('runtime/components/ComposeIconOverview.vue'),
        });

        // 9. Generate the icons index file
        const iconsIndexContent = generateIconsIndex(generatedComponents);
        await writeFile(assertAbsolute(resolve(componentsDir, 'index.ts')), iconsIndexContent);

        /**
         * TODO: description
         */
        // addTypeTemplate({
        //   filename: 'types/my-module.d.ts',
        //   getContents: () => `// Generated by my-module
        // declare module 'nuxt-compose-icons' {
        //   export { useComposeIcon, useComposeIconRegistry } from 'nuxt-compose-icons/dist/runtime/composables';
        // }
        // declare module 'nuxt-compose-icons/composables' {
        //   export { useComposeIcon, useComposeIconRegistry } from 'nuxt-compose-icons/dist/runtime/composables';
        // }
        // declare module 'nuxt-compose-icons/utils' {
        //   export { generateColorVariable, getIconSizeClass } from 'nuxt-compose-icons';
        //   export { useComposeIcon, useComposeIconRegistry } from 'nuxt-compose-icons/dist/runtime/composables/compose-icon';
        // }
        // declare module 'nuxt-compose-icons/types' {
        //   export { IconSize } from 'nuxt-compose-icons';
        //   export type {
        //     ComposeIconProps,
        //     ComposeIconSize,
        //     IconSizeKey,
        //     IconSizeKeyValue,
        //   } from 'nuxt-compose-icons';
        // }
        // declare module 'nuxt-compose-icons/components' {
        //   export * from ${JSON.stringify(componentsDir)}
        // }`,
        // });

        // addImports({
        //   name: 'useComposeIcon', // name of the composable to be used
        //   as: 'useComposeIcon',
        //   from: resolve('runtime/composables/compose-icon'), // path of composable
        // });
        // nuxt.hook('components:dirs', (dirs) => {
        //   dirs.push({
        //     path: path.resolve(__dirname, './runtime/components/icon-generated'),
        //     prefix: 'Compose',
        //   });
        // });
        for (const c of generatedComponents) {
          addComponent({
            name: c.pascalName,
            filePath: c.filePath,
          });
        }

        logger.info(
          `📦 ${generatedComponents.length} components generated and registered from ${componentsDir}`,
        );

        // 10. Generate the icon registry file
        const templateDir = resolveBuild('compose-icons');
        const useCustomDir = componentsDir !== templateDir;

        let registryPath: string;

        if (useCustomDir) {
          // Custom componentsDestDir: write registry there (alias points directly to it).
          // No need for a .nuxt copy — paths are already correct relative to componentsDir.
          const iconsRegistryContent = await generateIconsRegistry(
            generatedComponents,
            componentsDir,
          );
          registryPath = path.join(componentsDir, 'icon-registry.ts');
          await writeFile(assertAbsolute(registryPath), iconsRegistryContent);
        } else {
          // Default (.nuxt/compose-icons): use addTemplate so Nuxt manages the file lifecycle.
          const templateRegistryContent = await generateIconsRegistry(
            generatedComponents,
            templateDir,
          );
          const registryTemplate = addTemplate({
            filename: 'compose-icons/icon-registry.ts',
            getContents: () => templateRegistryContent,
            write: true,
          });
          registryPath = registryTemplate.dst;
        }

        // Make #compose-icons/registry resolvable in Vite's transform phase (client + SSR)
        nuxt.options.alias['#compose-icons/registry'] = registryPath;

        // In SPA mode Nitro never imports the composables, so the hooks below are
        // only needed for SSR builds.
        if (nuxt.options.ssr) {
          // Make #compose-icons/registry resolvable in Nitro's alias resolver
          nuxt.hook('nitro:config', (nitroConfig) => {
            nitroConfig.alias ??= {};
            nitroConfig.alias['#compose-icons/registry'] = registryPath;
          });

          // Force Nitro to bundle nuxt-compose-icons so the alias is resolved at
          // bundle time — without this, Node.js throws ERR_PACKAGE_IMPORT_NOT_DEFINED
          // at runtime because #compose-icons/registry isn't in the package's imports field.
          nuxt.hook('nitro:config', (nitroConfig) => {
            const inline = nitroConfig.externals?.inline;
            nitroConfig.externals ??= {};
            nitroConfig.externals.inline = [
              ...(Array.isArray(inline) ? inline : inline ? [inline] : []),
              'nuxt-compose-icons',
            ];
          });

          // Nitro's Rollup has no Vue plugin; this plugin handles our script-only SFCs.
          const vueScriptPlugin = createVueScriptPlugin(componentsDir);
          nuxt.hook('nitro:config', (nitroConfig) => {
            nitroConfig.rollupConfig ??= {};
            const existing = Array.isArray(nitroConfig.rollupConfig.plugins)
              ? nitroConfig.rollupConfig.plugins
              : nitroConfig.rollupConfig.plugins
                ? [nitroConfig.rollupConfig.plugins]
                : [];
            nitroConfig.rollupConfig.plugins = [vueScriptPlugin, ...existing];
          });
        }

        // 8. Add composables
        addImports([
          { name: 'useComposeIcon', from: resolve('runtime/composables/use-compose-icon') },
          {
            name: 'useComposeIconRegistry',
            from: resolve('runtime/composables/use-compose-icons-registry'),
          },
        ]);
        //     nuxt.hook('components:extend', async (components) => {
        //   for (const c of generatedComponents) {
        //     components.push({
        //       ...c,
        //     });
        //   }
        // });
      } else {
        logger.error(`Folder does not exist: ${absolutePathToIcons}`);
        throw new Error(`Folder does not exist: ${absolutePathToIcons}`);
      }
    } else if (iconComponentList) {
      // TODO: Think about re-implementing it or not
      Object.keys(iconComponentList).forEach((iconComponentName) => {
        logger.info('📟 - iconComponentName → ', iconComponentName);
        // const test = resolveComponent(iconComponentList[iconComponentName]);
        // TODO: Check if necessary to handle snake case as well
        // const componentName = toPascalCase(iconComponentName).replace(/&/g, 'And');
        // // const svgContent = ''; // Placeholder: you need to load the actual SVG content as needed
        // // const componentCode = createSvgComponentCode(componentName, svgContent);
        // // const componentCode = iconComponentList[iconComponentName];
        // const generatedFilePath = path.resolve(__dirname, './playground/icon-list.ts');
        // const component = createComponentFromName({
        //   ...options.generatedComponentOptions,
        //   name: componentName,
        //   shortPath: generatedFilePath,
        //   filePath: generatedFilePath,
        // });
        // nuxt.hook('components:extend', (components) => {
        //   components.push(component);
        // });
      });
    }
  },
});
