import type { Component } from '@nuxt/schema';
import * as path from 'node:path';
import { generateCommentLine, generateHeader } from '../template';

export { generateIconsIndex, generateIconsRegistry };

/**
 * Sort c
 *
 * @param {Component[]} components
 * @returns {Component[]}
 */
function sortComponents(components: Component[]): Component[] {
  return [...components].sort((a, b) =>
    (a.pascalName || a.kebabName || '').localeCompare(b.pascalName || b.kebabName || ''),
  );
}

function generateIconsIndex(components: Component[]) {
  const sortedComponents = sortComponents(components);

  const exports = sortedComponents
    .map((c) => {
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      return `export { default as ${c.pascalName || base} } from './${base}';`;
    })
    .join('\n');

  return `// Auto-generated by nuxt-compose-icons. Feel free to version this file, but do not edit directly as it will be overwritten at build time.

${exports}
`;
}

async function generateIconsRegistry(components: Component[]) {
  const sortedComponents = sortComponents(components);
  const registryPath = path.resolve('../runtime/utils/icon-registry.ts');

  const entries = sortedComponents
    .map((c) => {
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      const pascal = c.pascalName || base;
      const kebab = c.kebabName || base;
      return `  { name: '${pascal}', pascalName: '${pascal}', kebabName: '${kebab}', importPath: './${base}' },`;
    })
    .join('\n');

  // return `// Auto-generated by nuxt-compose-icons. Feel free to version this file, but do not edit directly as it will be overwritten at build time.
  return (
    generateHeader('Icon Registry') +
    generateCommentLine(
      'Auto-generated by nuxt-compose-icons. Feel free to version this file, but do not edit directly as it will be overwritten at build time.',
    ) +
    `
export interface IconRegistryEntry {
  name: string;
  pascalName: string;
  kebabName: string;
  importPath: string;
}

export const iconRegistryPath = ${JSON.stringify(registryPath.replace(/\\/g, '\\\\'))};

export const iconRegistry: IconRegistryEntry[] = [
${entries}
];
`
  );
}
