import type { Component } from '@nuxt/schema';
import * as path from 'node:path';
import { generateComment, generateESMExport } from './template';

export { generateIconsIndex };

/**
 * Sort components alphabetically by their pascalName or kebabName, falling back to file name if neither is available.
 *
 * @param {Component[]} components
 * @returns {Component[]}
 */
function sortComponents(components: Component[]): Component[] {
  return [...components].sort((a, b) =>
    (a.pascalName || a.kebabName || '').localeCompare(b.pascalName || b.kebabName || ''),
  );
}

/**
 * Generate the icons index file content.
 * Can be used in a case of a monorepo with multiple packages and you need to import icons manually.
 *
 * @param {Component[]} components
 * @returns {string}
 */
function generateIconsIndex(components: Component[]) {
  const sortedComponents = sortComponents(components);

  const exports = sortedComponents
    .map((c) => {
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      const importBase = path.basename(c.filePath).replace(/\.(ts|js)$/, '');

      return generateESMExport({
        moduleName: `default as ${c.pascalName || c.kebabName || base}`,
        path: `./${importBase}`,
      });
    })
    .join('');

  return (
    generateComment([
      'Auto-generated by nuxt-compose-icons.',
      'Feel free to version this file, but do not edit directly as it will be overwritten at build time.',
    ]) +
    `

${exports}
`
  );
}
