import type { Component } from '@nuxt/schema';
import * as path from 'node:path';
import { generateComment, generateHeader } from './template';

export { generateIconsIndex, generateIconsRegistry };

/**
 * Sort c
 *
 * @param {Component[]} components
 * @returns {Component[]}
 */
function sortComponents(components: Component[]): Component[] {
  return [...components].sort((a, b) =>
    (a.pascalName || a.kebabName || '').localeCompare(b.pascalName || b.kebabName || ''),
  );
}

function generateIconsIndex(components: Component[]) {
  const sortedComponents = sortComponents(components);

  const exports = sortedComponents
    .map((c) => {
      const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
      const importBase = path.basename(c.filePath).replace(/\.(ts|js)$/, '');
      return `export { default as ${c.pascalName || base} } from './${importBase}';`;
    })
    .join('\n');

  return (
    generateComment([
      'Auto-generated by nuxt-compose-icons.',
      'Feel free to version this file, but do not edit directly as it will be overwritten at build time.',
    ]) +
    `

${exports}
`
  );
}

async function generateIconsRegistry(components: Component[], registryDir: string) {
  const sortedComponents = sortComponents(components);

  const sortedEntries = sortedComponents.map((c) => {
    const base = path.basename(c.filePath).replace(/\.(ts|js|vue)$/, '');
    const pascal = c.pascalName || base;
    const kebab = c.kebabName || base;

    let importPath = path
      .relative(path.resolve(registryDir), path.resolve(c.filePath))
      .replace(/\.(ts|js)$/, '');

    if (!importPath.startsWith('.')) importPath = `./${importPath}`;
    return { pascal, kebab, importPath };
  });

  const imports = sortedEntries
    .map(({ pascal, importPath }) => `import ${pascal} from '${importPath}';`)
    .join('\n');

  const entries = sortedEntries
    .map(
      ({ pascal, kebab, importPath }) =>
        `  { name: '${pascal}', pascalName: '${pascal}', kebabName: '${kebab}', importPath: '${importPath}', component: ${pascal} },`,
    )
    .join('\n');

  return (
    generateHeader('Icon Registry') +
    generateComment([
      'Auto-generated by nuxt-compose-icons.',
      'Feel free to version this file, but do not edit directly as it will be overwritten at build time.',
    ]) +
    `
import type { Component } from 'vue';
${imports}

export interface IconRegistryEntry {
  name: string;
  pascalName: string;
  kebabName: string;
  importPath: string;
  component: Component;
}

export const iconRegistry: IconRegistryEntry[] = [
${entries}
];
`
  );
}
