name: Lint & Format & Test build

on:
  pull_request:

jobs:
  lint-format-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Playground prepare
        run: pnpm dev:prepare

      - name: Build the playground
        run: pnpm dev:build
