name: Lint & Format & Test build

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
        default: 20

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 8
          cache: 'pnpm'

      - name: ls
        run: ls -la && ls -la node_modules/

      - name: Lint
        run: pnpm lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 8
          cache: 'pnpm'

      - name: ls
        run: ls -la && ls -la node_modules/

      - name: Format
        run: pnpm format

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 8
          cache: 'pnpm'

      - name: ls
        run: ls -la && ls -la node_modules/

      - name: Test
        run: pnpm test
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 8
          cache: 'pnpm'

      - name: ls
        run: ls -la && ls -la node_modules/

      - name: Playground prepare
        run: pnpm dev:prepare

      - name: Build the playground
        run: pnpm dev:build
