name: Run Tests

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
        default: 20

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Install dependencies
#         uses: ./.github/actions/install-dependencies
#         with:
#           node_version: ${{ inputs.node_version }}
#           pnpm_version: 8
#           cache: 'pnpm'

#       - name: Playground prepare
#         run: pnpm dev:prepare

#       - name: Upload Playwright report
#         if: ${{ always() }}
#         run: |
#           mkdir -p test-results
#           ls -la
#       # - name: Install Playwright browsers
#       #   run: pnpm exec playwright-core install --with-deps

#       - name: Test
#         run: pnpm --filter nuxt-compose-icons test

#       - name: Upload Playwright report
#         uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: playwright-report
#           path: test-results/
#           retention-days: 30

#       - name: Upload Screenshot
#         if: ${{ !cancelled() }}
#         uses: actions/upload-artifact@v4
#         with:
#           name: playwright-report
#           path: test-results/screenshot.png
#           retention-days: 30
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: ${{ inputs.node_version }}
          pnpm_version: 8
          cache: pnpm

      - name: Prepare playground
        run: pnpm dev:prepare

      - name: Prep test-results dir
        run: mkdir -p packages/nuxt/test-results && ls -la && ls -la packages/nuxt/test-results

      - name: Install Playwright browsers
        run: pnpm exec playwright-core install --with-deps

      - name: Run tests
        run: pnpm --filter nuxt-compose-icons test

      - name: debug
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          ls -la packages/nuxt
          ls -la packages/nuxt/test-results

      - name: Upload HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.node_version }}
          path: packages/nuxt/test-results
          retention-days: 30

      - name: Upload Screenshot
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-${{ inputs.node_version }}
          path: packages/nuxt/screenshot.png
          retention-days: 30
